### ISSUE TITLE
[Parent ticket] Widget V2 todo list

### ISSUE THREAD

**Issue by vince19972** [Apybara/staking-xyz-widget#1]
This is a parent ticket that tracks all action items to deliver Widget V2.
- [Widget V2 RFC](https://github.com/Apybara/meta/blob/main/request-for-comments/20240227-widget-v2-roadmap.md)

### Product
- [x] Review [product planning RFC](https://github.com/Apybara/meta/pull/6) 

### UI/UX
- [x] Design core user flows in Figma
  - User wallet connection states on home view (wallet uninstalled, disconnected, connecting, connected)
  - Staking view and flow
  - Unstaking view and flow
  - Rewards view (with auto-compound feature) and flow
  - Activity view and flow

### Frontend
- [x] Set up project repo
- [x] Plan action items and tickets

### Backend
- [x] Complete BE requirements assessment [documents in planning RFC](https://github.com/Apybara/meta/pull/6) 

### UI/UX
- [x] Complete all missing components and states (e.g. empty states, loading states, error states, etc)
- ~~Design FAQs page~~
- ~~Design Privacy and agreements pages~~
- ~~Design landing page (optional? TBD)~~

### Frontend
- [x] Scaffold basic styling system
- [x] #5
  - Connection flows
  - Reading actions (balance, address, etc)
  - Setting actions (broadcast tx, sign message)
  - Network flows (switch between testnet and mainnet)
- [x] #6
- [x] #7
- [x] #15

### Backend
- [x] Evaluate and document API requirements and endpoints
- [x] Establish Celestia RPC and REST endpoints
- ~~Implement Postman mock endpoints~~

### Product
- [x] #45
- [x] Complete FAQs (and necessary legal docs) content

### UI/UX
- [x] Prepare meta materials (favicon, title, description, preview image)

### Frontend
- [x] #8
- [x] #9
- [x] #10
- [x] #11
- [x] #12
- [x] #24
- [x] #20
- [x] #21
- [x] #46
- [x] Use production meta materials (https://github.com/Apybara/staking-xyz-widget/issues/58)
~~Build FAQs page~~
~~Build landing page (optional? TBD)~~

### BE/FE integration
- [x] #22
- [x] #32
- [x] #49
- [x] #54
- [x] #31
- [x] #50
- [x] #64
- [x] #85
- [x] Nodes/endpoints updates (if necessary)
- [x] Fee receiver address update

### Product
- [x] Confirm domain usages between Widget V1 and V2 (#39)

### Frontend
- [x] Implement tracking tool events

### Launching checklist
- [x] Celestia endpoints
  - Mainnet REST - https://api.lunaroasis.net/
  - Mainnet RPC - https://rpc.lunaroasis.net/
  - Testnet REST - https://api-celestia-testnet-01.stakeflow.io/
  - Testnet RPC - https://rpc.celestia-mocha.com/
- [x] Fee receiving address - `celestia1nlfwe0vj07rqd8yyg04nef7thgwgut9syjrzjh`
- [ ] Remove Vercel password
- [x] #228

## P5: Deployment, monitoring, and next steps (2024/05/01)

_TBD_
