### ISSUE TITLE
[Parent ticket] Widget testing implementation roadmap (stage 1)

### ISSUE THREAD

**Issue by vince19972** [Apybara/staking-xyz-widget#189]
## Description
Implementing tests on FE is important but time-consuming. With our limited resources, we will strive to implement as many tests as possible by following these two principles:
1. 100% coverage is not our goal. We only need to covering critical areas.
2. Implementing tests should never prioritize over high-level feature or bug tasks.

## Target areas
Defining the critical areas is challenging though. For now (stage 1), let's focus on the following areas (which can be discussed and revised):
- **All number and currency conversion methods**:
  - This is important because we don't ever want to submit or show any inaccurate numbers, which impacts the UX and trust critically.
- **The input amount events, manipulation, and validations**: 
  - This would be a follow-up of the previous numbers implementation.
  - The complexity is hidden in the currency conversion logics.
- **Transaction procedures**:
  - These are the most complex flows to test against.
  - But this should be done to unblock #110.

## Challenges 
- Web3 packages are notoriously challenging to test against, mostly because of the wallets. 
  - There're some solutions, including [Synpress](https://github.com/Synthetixio/synpress), for mainstream wallets such as MetaMask, but I believe Keplr and Puzzle wallets don't have stable testing solutions. 
  - Therefore, I'd suggest to avoid testing all wallets-related methods/flows, such as connecting, disconnect, fetching balance, etc. If any states or data are needed, we can just mock the required values.
- React hooks can be a bit tricky to test against (at least it was tricky last time I checked). 

## Todos
- [ ] Investigate and decide testing libraries for unit tests and end-to-end tests
  - Unit test and end-to-end test can use different options, as long as the distinction doesn't result in any troubles. 
- [ ] Create a high-level plan and todo lists for the initial target area (e.g., the number and currency conversion methods)
  - For example, should we create unit tests for all methods? Where do we need end-to-end test?
- [ ] Implement the initial target area testing
- [ ] Create follow-up high-level plan and todo lists based on the initial implementation effort
