### ISSUE TITLE
Add "claims" tab to activity table

### ISSUE THREAD

**Issue by vince19972** [Apybara/staking-xyz-widget#241]
## Todos
- [ ] Add "claims" tab/filter to activity table
- [ ] Integrate new claims activity filter
- [ ] Remove "View history" button on rewards page
- [ ] Revise "View activity" link in claiming procedure dialog to "/activity" page
