### ISSUE TITLE
[Parent ticket] CosmosHub todo list

### ISSUE THREAD

**Issue by vince19972** [Apybara/staking-xyz-widget#256]
This is a parent ticket that tracks all action items to support Cosmos Hub on the frontend.

## Materials
- [High-level roadmap](https://github.com/Apybara/meta/blob/main/request-for-comments/20240530-staking-xyz-Q2-Q3-roadmap.md) 
- [Back-end todo list](https://github.com/orgs/Apybara/projects/2/views/14?pane=issue&itemId=66993604) 

## P1: Design and planning (2024/06/03 - 2024/06/05)
- [x] Confirm UI/UX changes in Figma
- [x] #257

## P2: Scaffolding and adjustments (2024/06/05 - 2024/06/07)
- [x] #260
- [x] #261
- [x] ~~Prototype Binance Wallet integration~~
  - After the investigation, decide to take Binance Wallet off from the requirement list. Details are documented in #257. 

### Frontend and product
- [x] #262
- [x] #263

### API integration required (mainnet and testnet)
- [x] #275
- [x] #276
- [x] #277
- [x] #278
- [x] #280
- [x] #279
- [x] #281

## P4: Testing and release (2024/06/12 - 2024/06/19)
- [x] Confirm endpoints
  - Mainnet REST: https://cosmos-rest.publicnode.com/
  - Mainnet RPC: https://cosmos-rpc.publicnode.com/
  - Testnet REST: https://rest.sentry-01.theta-testnet.polypore.xyz/
  - Testnet RPC: https://rpc.sentry-01.theta-testnet.polypore.xyz/
- [x] Remove Cosmos Hub option toggle feature flag
