### ISSUE TITLE
[Parent ticket] Aleo todo list

### ISSUE THREAD

**Issue by vince19972** [Apybara/staking-xyz-widget#294]
This is a parent ticket that tracks all action items to support Aleo on the frontend.

## Materials
- [High-level roadmap](https://github.com/Apybara/meta/blob/main/request-for-comments/20240530-staking-xyz-Q2-Q3-roadmap.md) 
- [Figma draft](https://www.figma.com/design/x0UYcu6LveNx73QAVcHswv/Aleo(widget-v2)-Draft?node-id=0-1&m=dev)

## P1: Design and planning (2024/06/10 - 2024/06/21)
- [x] Confirm UI/UX changes in Figma

## P2: Scaffolding and adjustments (2024/06/24 - 2024/06/28)
- [x] #307
- [x] #308
- [x] #309

### Product
- [x] #310

### Frontend
- [x] #311
- [x] #324
- [x] #312
- [x] #313
- [x] #314
- [x] ~~Build validators selection UI and flow~~
- [x] #315
- [x] #317
- [x] #340
- [x] #356
- [x] #364
- [x] #377
- [x] #380
- [x] #403
- [x] #404
- [x] #413
- [x] #467 
- [x] #461 

### API integration required (mainnet and testnet)
- [x] #325
- [x] #326
- [x] #346
- [x] #347
- [x] Integrate Aleo withdraw flow
- [x] #365
- [x] #366
- [x] #372
- [x] #373
- [x] #374
- [x] #316
- [x] #318

### Mainnet genesis: production launch (2024/09/04-2024/09/06)
- [x] #393
- [x] Remove Aleo option toggle feature flag
- [x] #341
- [x] #391
- [x] #400

### Coinbase Quest: Aleo-specific instance production launch (2024/09/05 - 2024/10/02)
- [x] #319
- [x] #334
