### ISSUE TITLE
Implement unbonding-validator staking guard

### ISSUE THREAD

**Issue by vince19972** [Apybara/staking-xyz-widget#404]
## Description
To resolve the stake-to-unbonding-validator [problem we found](https://github.com/Apybara/staking-xyz-widget/issues/392), FE needs to check if a validator is unbonding and disable stake button when:
1. If an address has staked balance already
2. If the specific-validator view is active

## Todo
- [x] [Design and prepare unbonding-validator state UI and warning message ](https://github.com/Apybara/product/issues/8)
- [ ] Implement FE procedure to check validator's unbonding status
- [ ] Integrate FE unbonding-validator state UI and warning message
